version: 0.2
build:
  commands:
    - echo Building...
artifacts:
  files:
    - index.html
    - appspec.yml
    - before_install.sh
    - restart_server.sh
  base-directory:
    ./talk-demos/appdeployment/SimplePage